[package]
name = "smoke-tests"
description = "0L end to end tests"
version = "0.1.0"

[dependencies]
aptos-cached-packages = { workspace = true }
aptos-debugger = { workspace = true }
aptos-forge = { workspace = true }
aptos-types = { workspace = true }